/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_final_casafolclore.GUI;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyecto_final_casafolclore.BaseDatos.conexionBD;
import static proyecto_final_casafolclore.BaseDatos.conexionBD.getConexion;
import proyecto_final_casafolclore.BaseDatos.registrarTraje;
import proyecto_final_casafolclore.Logica.RepoInventario;

/**
 *
 * @author OS
 */
public class GUI_inventario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUI_inventario.class.getName());

    /**
     * Creates new form GUI_inventario
     */
    public GUI_inventario() {
        initComponents();
        setLocationRelativeTo(null); //centrado
        setResizable(false); //no deja maximizar, mas rapido aqui
        Cargar_tabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlPantalla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bd_inventariooo = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_idtraje = new javax.swing.JTextField();
        txt_nombreTraje = new javax.swing.JTextField();
        cbo_genero = new javax.swing.JTextField();
        cbo_talla = new javax.swing.JTextField();
        txt_precio = new javax.swing.JTextField();
        lbl_estadoContrato = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final_casafolclore/GUI/Imagenes/franja.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pnlPantalla.setBackground(new java.awt.Color(249, 243, 234));

        bd_inventariooo.setBackground(new java.awt.Color(249, 243, 234));
        bd_inventariooo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 192, 145), 2));
        bd_inventariooo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bd_inventariooo.setSelectionBackground(new java.awt.Color(102, 102, 102));
        bd_inventariooo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bd_inventarioooMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bd_inventariooo);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("== I N V E N T A R I O ==");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Invetario y disponibilidad de trajes");

        jPanel1.setBackground(new java.awt.Color(249, 243, 234));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(219, 177, 114))));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("DETALLE TRAJE.");

        jLabel5.setText("ID Traje: ");

        jLabel6.setText("Nombre:");

        jLabel7.setText("Género:");

        jLabel8.setText("Talla:");

        jLabel9.setText("Monto:");

        jLabel10.setText("Disponibilidad:");

        txt_idtraje.setEditable(false);
        txt_idtraje.setBackground(new java.awt.Color(224, 192, 145));

        txt_nombreTraje.setEditable(false);
        txt_nombreTraje.setBackground(new java.awt.Color(224, 192, 145));
        txt_nombreTraje.addActionListener(this::txt_nombreTrajeActionPerformed);

        cbo_genero.setEditable(false);
        cbo_genero.setBackground(new java.awt.Color(224, 192, 145));

        cbo_talla.setEditable(false);
        cbo_talla.setBackground(new java.awt.Color(224, 192, 145));

        txt_precio.setEditable(false);
        txt_precio.setBackground(new java.awt.Color(224, 192, 145));

        lbl_estadoContrato.setEditable(false);
        lbl_estadoContrato.setBackground(new java.awt.Color(224, 192, 145));

        jButton1.setBackground(new java.awt.Color(224, 183, 123));
        jButton1.setText("Salir");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setBackground(new java.awt.Color(224, 200, 165));
        jButton2.setText("Reporte");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_idtraje, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(txt_nombreTraje)
                    .addComponent(cbo_genero)
                    .addComponent(cbo_talla)
                    .addComponent(txt_precio)
                    .addComponent(lbl_estadoContrato))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_idtraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_nombreTraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbo_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbo_talla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lbl_estadoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlPantallaLayout = new javax.swing.GroupLayout(pnlPantalla);
        pnlPantalla.setLayout(pnlPantallaLayout);
        pnlPantallaLayout.setHorizontalGroup(
            pnlPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPantallaLayout.createSequentialGroup()
                .addGroup(pnlPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(pnlPantallaLayout.createSequentialGroup()
                        .addGroup(pnlPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPantallaLayout.createSequentialGroup()
                                .addGap(304, 304, 304)
                                .addComponent(jLabel2))
                            .addGroup(pnlPantallaLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(pnlPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlPantallaLayout.setVerticalGroup(
            pnlPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPantallaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlPantallaLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        new MenuAdmin().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_nombreTrajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreTrajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreTrajeActionPerformed

    private void bd_inventarioooMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bd_inventarioooMouseClicked
     int filaSeleccionada = bd_inventariooo.getSelectedRow();
    
    if (filaSeleccionada >= 0) {
        // 1. Extraemos los datos que la JTable sí nos muestra en pantalla
        String idTraje = bd_inventariooo.getValueAt(filaSeleccionada, 0).toString().trim();
        String nombre = bd_inventariooo.getValueAt(filaSeleccionada, 1).toString().trim();
        String precio = bd_inventariooo.getValueAt(filaSeleccionada, 2).toString().trim();
        String estadoTraje = bd_inventariooo.getValueAt(filaSeleccionada, 3).toString().trim(); 

        // 2. Asignamos de inmediato lo que ya tenemos seguro
        txt_idtraje.setText(idTraje);
        txt_nombreTraje.setText(nombre);
        txt_precio.setText(precio);
        lbl_estadoContrato.setText(estadoTraje.toUpperCase());
        
        // 3. Consulta limpia usando SELECT * para evitar errores con los nombres de columnas
        String sqlBackup = "SELECT * FROM traje WHERE id_traje = ?";
        
        try (java.sql.Connection con = conexionBD.getConexion(); // Si te da error, usa la ruta larga: proyecto_final_casafolclore.BaseDatos.conexionBD.getConexion()
             java.sql.PreparedStatement pst = con.prepareStatement(sqlBackup)) {
            
            if (con != null) {
                pst.setString(1, idTraje);
                try (java.sql.ResultSet rs = pst.executeQuery()) {
                    if (rs.next()) {
                        
                        // INTENTO 1: Buscamos dinámicamente si tus columnas se llaman 'para' o 'genero'
                        String generoDetectado = "";
                        try { 
                            generoDetectado = rs.getString("para"); 
                        } catch (Exception e) {
                            try { generoDetectado = rs.getString("genero"); } catch (Exception ex) { generoDetectado = "M/F"; }
                        }
                        
                        String tallaDetectada = "";
                        try { 
                            tallaDetectada = rs.getString("talla"); 
                        } catch (Exception e) { 
                            tallaDetectada = "S/M/L"; 
                        }
                        
                        // Seteamos los textos finales en mayúsculas
                        cbo_genero.setText(generoDetectado.toUpperCase());
                        cbo_talla.setText(tallaDetectada.toUpperCase());
                    }
                }
            }
        } catch (Exception e) {
            // Si sale algún error inesperado de conexión, te lo mostrará en pantalla para saber qué es
            javax.swing.JOptionPane.showMessageDialog(this, "Error de conexión: " + e.getMessage());
            cbo_genero.setText("ERROR");
            cbo_talla.setText("ERROR");
        }
        
        // 4. Cambiamos el color de la disponibilidad (¡Con tu color morado funcionando!)
        if ("DISPONIBLE".equalsIgnoreCase(estadoTraje)) {
            lbl_estadoContrato.setForeground(new java.awt.Color(0, 153, 51)); // Verde
        } else if ("RESERVADO".equalsIgnoreCase(estadoTraje)) {
            lbl_estadoContrato.setForeground(new java.awt.Color(128, 0, 128)); // Morado
        } else {
            lbl_estadoContrato.setForeground(new java.awt.Color(204, 0, 0)); // Rojo para ALQUILADO
        }
    }
    
    }//GEN-LAST:event_bd_inventarioooMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        RepoInventario report = new RepoInventario();
        report.GenerarReporte(bd_inventariooo);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUI_inventario().setVisible(true));
    }
    
    public void Cargar_tabla(){
        
       DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID Traje");
        modelo.addColumn("Nombre");
        modelo.addColumn("Precio");
        modelo.addColumn("Estado Traje"); // Cambiado a Estado del Traje directamente

        bd_inventariooo.setModel(modelo);

        // Consulta directa: Leemos el estado real del traje directamente de su tabla
        String sql = "SELECT id_traje, nombre_traje, precio_traje, estado FROM traje ORDER BY id_traje ASC";

        try (Connection cn = getConexion(); // Si te da error getConexion(), usa conexionBD.getConexion()
             PreparedStatement pst = cn.prepareStatement(sql);
             ResultSet rs = pst.executeQuery()) {

            String[] datos = new String[4];

            while (rs.next()) {
                datos[0] = rs.getString("id_traje");
                datos[1] = rs.getString("nombre_traje");
                datos[2] = rs.getString("precio_traje");

                // Leemos la columna 'estado' de la tabla 'traje'
                String estado = rs.getString("estado"); 
                if (estado == null || estado.trim().isEmpty()) {
                    datos[3] = "DISPONIBLE"; 
                } else {
                    datos[3] = estado.toUpperCase().trim(); // Traerá "ALQUILADO" o "DISPONIBLE" según lo que guardó el pago
                }

                modelo.addRow(datos);
            }

            bd_inventariooo.setModel(modelo);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar la lista de trajes: " + e.getMessage());
            e.printStackTrace();
        }
        
    }
    
    public void buscarYMostrarTraje(String idTraje) {
    String sql = "SELECT t.id_traje,t.nombre_traje, t.genero, t.talla, t.precio_traje, c.estado_contrato " +
                 "FROM traje t " +
                 "LEFT JOIN contrato_alquiler c ON t.id_traje = c.id_traje " +
                 "AND c.id_contrato_alquiler = (SELECT MAX(id_contrato_alquiler) " +
                 "                              FROM contrato_alquiler " +
                 "                              WHERE id_traje = t.id_traje) " +
                 "WHERE t.id_traje = ?";
                 
    // Nos conectamos directamente usando el método getConexion() de tu proyecto
    try (Connection cn = getConexion();
         PreparedStatement pst = cn.prepareStatement(sql)) {
        
        pst.setString(1, idTraje);
        
        try (ResultSet rs = pst.executeQuery()) {
            if (rs.next()) {
                // Asignamos los datos directamente a cada JTextField independiente
                txt_idtraje.setText(rs.getString("id_traje"));
                txt_nombreTraje.setText(rs.getString("nombre_traje"));
                cbo_genero.setText(rs.getString("genero"));
                cbo_talla.setText(rs.getString("talla"));
                txt_precio.setText(rs.getString("precio_traje"));
                
                // Extraemos el estado del contrato
                String estado = rs.getString("estado_contrato");
                
                if (estado == null) {
                    lbl_estadoContrato.setText("DISPONIBLE");
                    lbl_estadoContrato.setForeground(new java.awt.Color(0, 153, 51)); // Verde
                } else {
                    lbl_estadoContrato.setText(estado.toUpperCase());
                    
                    // Si está alquilado o activo, lo pone en naranja, si no, en azul
                    if (estado.equalsIgnoreCase("Activo") || estado.equalsIgnoreCase("Alquilado")) {
                        lbl_estadoContrato.setForeground(new java.awt.Color(255, 153, 0)); // Naranja
                    } else {
                        lbl_estadoContrato.setForeground(new java.awt.Color(0, 102, 204)); // Azul
                    }
                }
                
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró ningún traje con el ID: " + idTraje, "Aviso", JOptionPane.INFORMATION_MESSAGE);
                limpiarCampos(); // Vacía los campos si el ID no existe
            }
        }
        
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al consultar la base de datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}
    
    private void limpiarCampos() {
    txt_nombreTraje.setText("");
    cbo_genero.setText("");
    cbo_talla.setText("");
    txt_precio.setText("");
    
    lbl_estadoContrato.setText("Estado: -");
    lbl_estadoContrato.setForeground(java.awt.Color.BLACK); 
}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bd_inventariooo;
    private javax.swing.JTextField cbo_genero;
    private javax.swing.JTextField cbo_talla;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lbl_estadoContrato;
    private javax.swing.JPanel pnlPantalla;
    private javax.swing.JTextField txt_idtraje;
    private javax.swing.JTextField txt_nombreTraje;
    private javax.swing.JTextField txt_precio;
    // End of variables declaration//GEN-END:variables
}
