/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_final_casafolclore.GUI;

/**
 *
 * @author neyli
 */
public class MenuAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuAdmin.class.getName());

    /**
     * Creates new form MenuAdmin
     */
    public MenuAdmin() {
        initComponents();
        setSize(900, 600); //tamaño
        setLocationRelativeTo(null); //centrado
        setResizable(false); //no deja maximizar, mas rapido aqui
    }
    
    public MenuAdmin(String correo) { //segundo constructor para correo, no quiero arriesgarme Debe cambiar con base de datos
        initComponents();
        lblSaludo.setText("Bienvenido/a, " + correo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pblEntrada = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        lblSaludo = new javax.swing.JLabel();
        pnlDashboard = new javax.swing.JPanel();
        btnGAlquiler = new javax.swing.JButton();
        btnGTrajes = new javax.swing.JButton();
        btnGCliente3 = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        btnGPago = new javax.swing.JButton();
        lblOpciones = new javax.swing.JLabel();
        pnlPantalla = new javax.swing.JPanel();
        lblMensaje = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);

        pblEntrada.setBackground(new java.awt.Color(153, 102, 0));
        pblEntrada.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnLogout.setBackground(new java.awt.Color(204, 204, 204));
        btnLogout.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(0, 51, 51));
        btnLogout.setText("Cerrar sesión");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        lblSaludo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblSaludo.setForeground(new java.awt.Color(255, 255, 255));
        lblSaludo.setText("Bienvenido/a,");

        javax.swing.GroupLayout pblEntradaLayout = new javax.swing.GroupLayout(pblEntrada);
        pblEntrada.setLayout(pblEntradaLayout);
        pblEntradaLayout.setHorizontalGroup(
            pblEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pblEntradaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblSaludo, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(33, 33, 33))
        );
        pblEntradaLayout.setVerticalGroup(
            pblEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pblEntradaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pblEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSaludo)
                    .addComponent(btnLogout))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pnlDashboard.setBackground(new java.awt.Color(51, 51, 51));

        btnGAlquiler.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnGAlquiler.setText("Registrar alquiler");
        btnGAlquiler.addActionListener(this::btnGAlquilerActionPerformed);

        btnGTrajes.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnGTrajes.setText("Gestionar trajes");
        btnGTrajes.addActionListener(this::btnGTrajesActionPerformed);

        btnGCliente3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnGCliente3.setText("Registrar cliente");
        btnGCliente3.addActionListener(this::btnGCliente3ActionPerformed);

        btnInventario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnInventario.setText("Ver inventario");
        btnInventario.addActionListener(this::btnInventarioActionPerformed);

        btnGPago.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnGPago.setText("Registrar pago");
        btnGPago.addActionListener(this::btnGPagoActionPerformed);

        lblOpciones.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblOpciones.setForeground(new java.awt.Color(255, 255, 255));
        lblOpciones.setText("DASHBOARD");

        javax.swing.GroupLayout pnlDashboardLayout = new javax.swing.GroupLayout(pnlDashboard);
        pnlDashboard.setLayout(pnlDashboardLayout);
        pnlDashboardLayout.setHorizontalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnGCliente3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGTrajes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGAlquiler, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(btnGPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        pnlDashboardLayout.setVerticalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblOpciones)
                .addGap(44, 44, 44)
                .addComponent(btnGCliente3)
                .addGap(18, 18, 18)
                .addComponent(btnGTrajes)
                .addGap(18, 18, 18)
                .addComponent(btnGAlquiler)
                .addGap(18, 18, 18)
                .addComponent(btnGPago)
                .addGap(18, 18, 18)
                .addComponent(btnInventario)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pnlPantalla.setBackground(new java.awt.Color(204, 204, 204));

        lblMensaje.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        lblMensaje.setForeground(new java.awt.Color(102, 102, 102));
        lblMensaje.setText("¿Qué deseas hacer hoy?");

        javax.swing.GroupLayout pnlPantallaLayout = new javax.swing.GroupLayout(pnlPantalla);
        pnlPantalla.setLayout(pnlPantallaLayout);
        pnlPantallaLayout.setHorizontalGroup(
            pnlPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPantallaLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        pnlPantallaLayout.setVerticalGroup(
            pnlPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPantallaLayout.createSequentialGroup()
                .addContainerGap(199, Short.MAX_VALUE)
                .addComponent(lblMensaje)
                .addGap(156, 156, 156))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final_casafolclore/GUI/Imagenes/franja.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(pnlDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pblEntrada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pblEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // coton cerrar sesion
        InicioSesion login = new InicioSesion();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnGCliente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGCliente3ActionPerformed
        // boton registro cliente
    }//GEN-LAST:event_btnGCliente3ActionPerformed

    private void btnGTrajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGTrajesActionPerformed
        // boton gestion traje
    }//GEN-LAST:event_btnGTrajesActionPerformed

    private void btnGAlquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGAlquilerActionPerformed
        // boton registro alquiler
    }//GEN-LAST:event_btnGAlquilerActionPerformed

    private void btnGPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGPagoActionPerformed
        // boton registro pago
    }//GEN-LAST:event_btnGPagoActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        // boton inventario
    }//GEN-LAST:event_btnInventarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGAlquiler;
    private javax.swing.JButton btnGCliente3;
    private javax.swing.JButton btnGPago;
    private javax.swing.JButton btnGTrajes;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblOpciones;
    private javax.swing.JLabel lblSaludo;
    private javax.swing.JPanel pblEntrada;
    private javax.swing.JPanel pnlDashboard;
    private javax.swing.JPanel pnlPantalla;
    // End of variables declaration//GEN-END:variables
}
