<?xml version="1.0" encoding="UTF-8"?>
<project name="Proyecto_Final_CasaFolclore" default="default" basedir=".">
    <description>Builds, tests, and runs the project Proyecto_Final_CasaFolclore.</description>
    <import file="nbproject/build-impl.xml"/>

    <property name="launch4j.dir" location="C:/Program Files (x86)/Launch4j" />

    <taskdef name="launch4j"
             classname="net.sf.launch4j.ant.Launch4jTask"
             classpath="${launch4j.dir}/launch4j.jar:${launch4j.dir}/lib/xstream.jar" />

    <target name="-post-jar">
        <echo message="Generando archivo ejecutable .EXE en el Escritorio..."/>
        <launch4j>
            <config dontWrapJar="false"
                    headerType="gui"
                    jar="C:\Users\OS\Documents\NetBeansProjects\Proyecto_Final_CasaFolclore\dist\Proyecto_Final_CasaFolclore.jar"
                    outfile="C:\Users\OS\Desktop\CasasFolclor.exe"
                    priority="normal"
                    stayAlive="false"
                    restartOnCrash="false"
                    icon="C:\Users\OS\Downloads\costume_rental_icon.ico">
                
                <jre path="%JAVA_HOME%;%PATH%"
                     requiresJdk="false"
                     requires64Bit="false"
                     minVersion="1.8"
                     maxVersion="25.0" />
            </config>
        </launch4j>
    </target>
    
</project>